In [43]:
import numpy as np
np.random.seed(0)
A = np.random.randint(0,10,[4,1])
B = np.ones((3,))
A+B

array([[6., 6., 6.],
       [1., 1., 1.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [44]:
A

array([[5],
       [0],
       [3],
       [3]])

In [45]:
B

array([1., 1., 1.])

In [26]:
A + B


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [60]:
np.random.seed(0)
A = np.random.randint(0,100,[10,5])
print(A)

D = (A - A.mean(axis=0)) / A.std(axis=0)
print(D,"\n moyenne : ",np.mean(D,axis=0),"\n ecart-type :",np.std(D))
A.mean(axis=0)

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]
 [ 9 20 80 69 79]
 [47 64 82 99 88]
 [49 29 19 19 14]
 [39 32 65  9 57]
 [32 31 74 23 35]]
[[-0.02206157  0.          0.13173823  0.72539252  0.10755798]
 [-1.56637126  1.61579632 -1.48676006 -0.33034307  0.96802178]
 [ 1.12513992  1.84021247  1.03508612 -1.14768676 -0.27965074]
 [ 0.90452425 -0.35906585  0.99744662  0.0102168   1.01104497]
 [ 1.6104944  -0.44883231 -1.33620208  1.0659524   0.32267393]
 [-1.56637126 -1.21184724  0.73397016  0.7935045   0.62383626]
 [ 0.11030784  0.76301493  0.80924915  1.81518411  1.01104497]
 [ 0.1985541  -0.80789816 -1.56203905 -0.90929485 -2.17267111]
 [-0.24267724 -0.67324847  0.16937773 -1.24985473 -0.32267393]
 [-0.55153918 -0.7181317   0.50813319 -0.77307091 -1.26918412]] 
 moyenne :  [-2.22044605e-17 -4.44089210e-17  0.00000000e+00 -1.22124533e-16
 -4.44089210e-17] 
 ecart-type : 1.0


array([44.5, 47. , 60.5, 45.7, 64.5])