In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris


In [15]:
iris = load_iris()

x = iris.data
y = iris.target
names = list(iris.target_names)

print(f'x contient {x.shape[0]} exe mples {x.shape[1]} variables')
print(f'il y a {np.unique(y).size} classes')

plt.scatter(x[:,0],x[:,1],c=y,alpha=0.5,s=x[:,2]*25)
plt.xlabel("longueur sepal")
plt.ylabel("largeur sepal")


x contient 150 exe mples 4 variables
il y a 3 classes


Text(0, 0.5, 'largeur sepal')

In [ ]:
from mpl_toolkits.mplot3d import Axes3D



In [9]:
%matplotlib
ax = plt.axes(projection="3d")
ax.scatter(x[:,0],x[:,1],x[:,2],c=y)

Using matplotlib backend: QtAgg


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [11]:
f = lambda x,y : np.sin(x) + np.cos(y)
x = np.linspace(0,5,100)
y = np.linspace(0,5,100)
X,Y = np.meshgrid(x,y)
Z=f(X,Y)
ax = plt.axes(projection="3d")
ax.plot_surface(X,Y,Z,cmap="plasma")

In [19]:
plt.hist(x[:,0],bins=100)
plt.hist(x[:,1],bins=100)

(array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
         0.,  0.,  0.,  3.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  5.,
         0.,  0.,  0.,  9.,  0.,  0.,  0., 14.,  0.,  0.,  0., 10.,  0.,
         0.,  0., 26.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0., 13.,  0.,
         0.,  0.,  6.,  0.,  0.,  0., 12.,  0.,  0.,  0.,  6.,  0.,  0.,
         0.,  4.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  6.,  0.,  0.,  0.,
         0.,  2.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]),
 array([2.   , 2.024, 2.048, 2.072, 2.096, 2.12 , 2.144, 2.168, 2.192,
        2.216, 2.24 , 2.264, 2.288, 2.312, 2.336, 2.36 , 2.384, 2.408,
        2.432, 2.456, 2.48 , 2.504, 2.528, 2.552, 2.576, 2.6  , 2.624,
        2.648, 2.672, 2.696, 2.72 , 2.744, 2.768, 2.792, 2.816, 2.84 ,
        2.864, 2.888, 2.912, 2.936, 2.96 , 2.984, 3.008, 3.032, 3.056,
        3.08 , 3.104, 3.128, 3.152, 3.176, 3.2  , 3.224, 3.248, 3.272,
        

In [22]:
plt.hist2d(x[:,0],x[:,1],cmap="Blues")
plt.xlabel("longueur sepal")
plt.ylabel("largeur sepal")
plt.colorbar()

In [25]:
from scipy import misc
face = misc.face(gray=True)
plt.hist(face.ravel(),bins=255)
plt.show()

In [28]:
plt.contour(X,Y,Z,20,colors="black")

In [31]:
plt.contourf(X,Y,Z,cmap="RdGy")
plt.colorbar()

In [35]:
plt.imshow(np.corrcoef(x.T),cmap='Blues')
plt.colorbar()
plt.show()
np.corrcoef(x)

array([[1.        , 0.99599866, 0.99997391, ..., 0.65347343, 0.6339168 ,
        0.63315839],
       [0.99599866, 1.        , 0.99660709, ..., 0.70898277, 0.68625679,
        0.68483481],
       [0.99997391, 0.99660709, 1.        , ..., 0.65755616, 0.63763128,
        0.6368058 ],
       ...,
       [0.65347343, 0.70898277, 0.65755616, ..., 1.        , 0.99570813,
        0.99446012],
       [0.6339168 , 0.68625679, 0.63763128, ..., 0.99570813, 1.        ,
        0.99991588],
       [0.63315839, 0.68483481, 0.6368058 , ..., 0.99446012, 0.99991588,
        1.        ]])